stages:
  - build

variables:
  CI_LANGUAGE: go
  CI_FOLDER: pkg


test:
  stage: build
  image: maven:3.5.4-jdk-8
  script:
    - ls ~/.m2/ 
    - find  ~/.m2/repository/ -name kohsuke
    - mvn -q package -Dmaven.test.skip=true 
    - ls ~/.m2/
  cache:
    key: maven-m2
    paths:
      - ~/.m2/